### ISSUE TITLE
WiFi credentials error

### ISSUE THREAD

**Issue by Dancopy** [balkian/ESP8266_Clock_NTP#1]
ESP8266_Clock_NTP:251:19: error: 'WIFI_SSID' was not declared in this scope

ESP8266_Clock_NTP:251:30: error: 'WIFI_PASS' was not declared in this scope

exit status 1
'WIFI_SSID' was not declared in this scope

I do not understand where to put the network name and password (SSID and Password);
Thank you

**Comment by Dancopy** [comment]
PS. I put my SSID and Password in the sketch here: wifiMulti.addAP ("Xxxxxxx", "xxxxxxxxxxx"); and I connected the pins as the schematic but, the display remains in white screen.

**Comment by balkian** [comment]
For future reference, those variables should be defined in a separate file (`passwords.h`), or you can replace the following line with the definition:

```
#include "passwords.h"  // Define WIFI_PASS and WIFI_SSID here
```
